### ISSUE TITLE
协议数据包存在不兼容情况

### ISSUE THREAD

**Issue by ghost** [ideawu/tftpx#1]
你实现的这个tftp客户端与服务器之间是可以正常运行，但是客户端与其他的tftp服务器无法正常工作

**Comment by ideawu** [comment]
"与其他服务器"是什么意思? "跑不起来"是什么意思?

**Comment by ghost** [comment]
不好意思,没说清楚,主要是我使用的是Win32版本下的tftpd32这个程序作为测试服务器,跑了一下你的客户端的get文件功能, 发现不成功所以就给你提了这个issue,没想到你回复了.

 是这样的, 你的客户端代码do_get函数发送tftp请求包的格式的格式可能与tftpd32这个服务器不兼容导致的, 你的代码发送Read request (RRQ)包的时候, 是这样的

``` C
snd_packet.cmd = htons(CMD_RRQ);
sprintf(snd_packet.filename, "%s%c%s%c%d%c", remote_file, 0, "octet", 0, blocksize, 0);
sendto(sock, &snd_packet, sizeof(struct tftpx_packet), 0, (struct sockaddr*)&server, addr_len);
```

注意数据包头的cmd占二字节, 是以网络字节序发送的, 而tftpd32在获取该包的时候, 不是以ntohs(snd_packet.cmd)来解析这个opcode, 而是以ascii码来解析的, 看一下它对应客户端代码你就明白了

``` C
// creates a request packet and returns lenght of packet
int req_packet (int opcode, char *filename, char *mode, char header[])
{
    int lenght;
    // format is for RRQ/WRQ : | 01/02 | Filename | 0 | Mode | 0
    lenght = sprintf (header, "%c%c%s%c%s%c", 0x00, opcode, filename, 0x00, mode, 0x00);
    if (lenght == 0)
    {
        printf ("Error in creating the request packet\n");
        exit(-1);
    }
    return lenght;
}
```

看到你回复这个issue我才找了一下对应的代码, 我当时自己试了下这位的客户端下载文件功能[https://github.com/raviteja-ksva/tftp](https://github.com/raviteja-ksva/tftp), 发现与tftpd32是兼容的, 所以直接改来用, 没太在意, 这个opcode到底是应该用short型发送还是使用assic,看一下这个RFC文档[http://www.ietf.org/rfc/rfc1350.txt](http://www.ietf.org/rfc/rfc1350.txt)给出的定义:

> > > ```
> > >       2 bytes    string   1 byte     string   1 byte
> > >       -----------------------------------------------
> > > ```
> > > 
> > >    RRQ/  | 01/02 |  Filename  |   0  |    Mode    |   0  |
> > >    WRQ    -----------------------------------------------
> > >           2 bytes    2 bytes       n bytes
> > >           ---------------------------------
> > >    DATA  | 03    |   Block #  |    Data    |
> > >           ---------------------------------
> > >           2 bytes    2 bytes
> > >           -------------------
> > >    ACK   | 04    |   Block #  |
> > >           --------------------
> > >           2 bytes  2 bytes        string    1 byte
> > >           ----------------------------------------
> > >    ERROR | 05    |  ErrorCode |   ErrMsg   |   0  |
> > >           ----------------------------------------

<<<
首部2字节的opcode文档描述的是01/02,因此可以确认其应该指的是ascii, 如果说他表示的是值的话, 应该直接用1/2来表示, 到底是ascii还是short型我就不去纠结了, 留给大神您去确认了

**Comment by ideawu** [comment]
@sijianwudi 你好, 很不幸, 你所使用的"Win32版本下的tftpd32"对tftp协议的opcode的理解是错误的! 请以linux系统下的tftp客户端命令为准.

此项目的server可以和linux系统下的tftp命令(http://linux.die.net/man/1/tftp )正常交互, 没有问题.

**Comment by ghost** [comment]
@ideawu 是我搞错了. opcode是以网络字节序列发送,下面这行代码
`sprintf (header, "%c%c%s%c%s%c", 0x00, opcode, filename, 0x00, mode, 0x00);`
得到的是opcode是网络字节序，对这个`%c`理解有误, 以为会将opcode转为ascci

因为看到很多路由器介绍刷固件都是使用tftpd32,我仅仅是在win32下测试你的客户端代码,发现不能成功获取文件,所以就给你提了这个issue,如有冒犯请见谅!

**Comment by ideawu** [comment]
没有冒犯的意思. 我不知道这个tftpd32是什么, 请问你是从哪里下载的? 这个tftpd32是否符合标准? 和linux自带的tftp命令是否能配合?

**Comment by ideawu** [comment]
我下载了这个 tftpd32 http://tftpd32.jounin.net/tftpd32_download.html, 无论是以这个 tftpd32 作为 server 还是 client, 都可以正常和我的 tftpx 正常配合. 请问, 你用的是哪个?

**Comment by ghost** [comment]
sorry,我是把你的代码移植到win32进行测试的,可能移植的时候改错了某些地方, 刚刚重新整理了一边, 能够正常运行了,打扰了thanks

**Comment by ideawu** [comment]
@sijianwudi 欢迎继续交流, 也可以把你移植的win32版本开源, 分享给其他人.
