### ISSUE TITLE
endian conversion problem in threaded request dispatcher

### ISSUE THREAD

**Issue by jrrk** [ideawu/tftpx#6]
// Choose handler
switch(request->packet.cmd){

This should be  switch(ntohs(request->packet.cmd)) in my view otherwise it will only work on big endian machines.

**Comment by ideawu** [comment]
request->packet.cmd has already been converted from network endian to host endian when received.

see: https://github.com/ideawu/tftpx/blob/master/server.c#L57
```
request->size = recvfrom(
		sock, &(request->packet), MAX_REQUEST_SIZE, 0,
		(struct sockaddr *) &(request->client), &addr_len);
request->packet.cmd = ntohs(request->packet.cmd);
```

**Comment by jrrk** [comment]
OK, that's my oversight.
